# Generated by Django 4.2.6 on 2024-01-18 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_userinfo_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('singer', models.CharField(max_length=20)),
                ('url', models.CharField(max_length=64)),
                ('count', models.IntegerField(default=0)),
                ('category', models.CharField(choices=[('pop', '流行'), ('rock', '摇滚'), ('jazz', '爵士'), ('classical', '古典'), ('folk', '民谣'), ('country', '乡村'), ('blues', '蓝调'), ('hiphop', '嘻哈'), ('heavy_metal', '重金属'), ('electronic', '电子')], default='pop', max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='phone',
            field=models.CharField(max_length=11),
        ),
        migrations.CreateModel(
            name='UserMusicCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pop_count', models.IntegerField(default=0)),
                ('rock_count', models.IntegerField(default=0)),
                ('jazz_count', models.IntegerField(default=0)),
                ('classical_count', models.IntegerField(default=0)),
                ('folk_count', models.IntegerField(default=0)),
                ('country_count', models.IntegerField(default=0)),
                ('blues_count', models.IntegerField(default=0)),
                ('hiphop_count', models.IntegerField(default=0)),
                ('heavy_metal_count', models.IntegerField(default=0)),
                ('electronic_count', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.userinfo')),
            ],
        ),
    ]
