# Generated by Django 4.2.6 on 2024-01-20 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_music_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='url',
            field=models.CharField(max_length=256),
        ),
    ]
