# Generated by Django 4.2.6 on 2024-01-23 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_music_name_alter_music_singer'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='lyric_url',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
