# Generated by Django 4.2.6 on 2024-01-25 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_music_lyric_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='pic_url',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
