# Generated by Django 4.2.6 on 2024-02-22 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_alter_music_publish_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='MusicSimilarity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('similarity', models.FloatField()),
                ('music', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='music', to='user.music')),
                ('similar_music', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similar_music', to='user.music')),
            ],
        ),
    ]
