# Generated by Django 4.2.6 on 2024-04-17 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_comment_like_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersimilarity',
            name='rank',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
