# Generated by Django 4.2.6 on 2024-04-17 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_usersimilarity_rank'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersimilarity',
            name='rank',
        ),
    ]
