# Generated by Django 4.2.6 on 2024-04-17 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_remove_usersimilarity_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='musicsimilarity',
            name='rank',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
